// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAId3yEKI8ZFug--BPjOi8lr1g4oMozssc',
    appId: '1:635564986945:web:d3a2264b2f44a1cc49acc0',
    messagingSenderId: '635564986945',
    projectId: 'bank-3deaa',
    authDomain: 'bank-3deaa.firebaseapp.com',
    storageBucket: 'bank-3deaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVs9GoBkFbNI3Y7NfF7VPFyZyYgj267gk',
    appId: '1:635564986945:android:f99e50d5ca2b273949acc0',
    messagingSenderId: '635564986945',
    projectId: 'bank-3deaa',
    storageBucket: 'bank-3deaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhxfSk5R5Va4ePqvtAGXdZJVMSu2A-7Y',
    appId: '1:635564986945:ios:4f8b20c28bf43c2049acc0',
    messagingSenderId: '635564986945',
    projectId: 'bank-3deaa',
    storageBucket: 'bank-3deaa.firebasestorage.app',
    iosBundleId: 'com.example.bank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwhxfSk5R5Va4ePqvtAGXdZJVMSu2A-7Y',
    appId: '1:635564986945:ios:4f8b20c28bf43c2049acc0',
    messagingSenderId: '635564986945',
    projectId: 'bank-3deaa',
    storageBucket: 'bank-3deaa.firebasestorage.app',
    iosBundleId: 'com.example.bank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAId3yEKI8ZFug--BPjOi8lr1g4oMozssc',
    appId: '1:635564986945:web:adf9bbc858abad2149acc0',
    messagingSenderId: '635564986945',
    projectId: 'bank-3deaa',
    authDomain: 'bank-3deaa.firebaseapp.com',
    storageBucket: 'bank-3deaa.firebasestorage.app',
  );
}
